import os
from pydantic import BaseModel, Field


class OutputResponseModel(BaseModel):
    """
    OutputResponseModel represents the response from the agent containing the output, email reference flag, and reasoning behind the email reference decision.

        Attributes:
            answer (str): The response generated for the user query.
            hasemailreference (bool | str): Indicates if the response contains references to email content (body, subject, follow-ups, or private/personal content).
            agentsused (list[str]): List of agents or tools used to generate the response.
            reasoning (str): Explanation of why the hasemailreference value was set to true or false.
    """

    answer: str = Field(
        ...,
        description=(
            "Provide the response generated for the user query.\n"
            "When generating a response, determine whether it is based solely on your internal knowledge or involves any tool calls, tool outputs, or interpretations derived from tools.\n"
            "If the response is entirely from your own knowledge (not influenced by any tool results), append the following line only once at the very end of the message, on a new line:\n"
            f"(*Generated by DKS AI using {os.environ.get('DKS_AZURE_OPENAI_DEPLOYMENT_NAME', 'gpt')}*)\n"
            "If the response uses or interprets any tool-generated data, do not include the above line.\n"
            "The suffix should only appear when the answer is directly produced by the LLM without referencing or summarizing tool outputs."
        ),
    )
    hasemailreference: bool | str = Field(
        ...,
        description=(
            "Set to true if the agent's response detects any references to email content, including email body, subject, follow-ups, or private/personal content derived from emails. Otherwise set to false. Can be a boolean or string."
        ),
    )
    agentsused: list[str] = Field(
        default=[],
        description="List of agents or tools used to generate the response. If no tools are used, return an empty array.",
    )
    reasoning: str = Field(
        ...,
        description="Explanation of why the hasemailreference value was set to true or false. The agent must clearly state the reasoning behind the decision",
    )
