"""
Models for chat request and response handling in the Orchestrator API.
Classes:
    ChatMessage:
        Represents a single chat message sent by either a user or an agent.
        Fields:
            role (str): Role of the message sender, either 'user' or 'agent'.
            id (Optional[str]): Unique identifier for the message, generated by default.
            parts (List[Union[TextPart, FilePart, DataPart]]): Content parts of the message, which can be text, file, or data.
            extensions (List[dict]): Optional list of extension metadata for the message.
    OrchestratorChatRequest:
        Represents a chat request to the orchestrator.
        Fields:
            conversationid (Optional[str]): Identifier for the conversation.
            message (Optional[ChatMessage]): The chat message being sent.
    ChatRequestErrorResponse:
        Represents an error response for a chat request.
        Fields:
            conversationid (Optional[str]): Identifier for the conversation related to the error.
            messageid (Optional[str]): Identifier for the message related to the error.
            error (str): Error message description.
            code (Optional[str]): Optional error code.
            details (Optional[dict]): Additional details about the error.
    ConversationMessage:
        Represents a chat message within a conversation, including creation time.
        Fields:
            createddatetime (datetime): Timestamp when the message was created.
            (Inherited fields from ChatMessage)
    ConversationResponse:
        Represents a response containing multiple conversation messages.
        Fields:
            messages (List[ConversationMessage]): List of messages in the conversation.
    AllConversationResponseItem:
        Represents summary information for a conversation.
        Fields:
            conversationid (str): Unique identifier for the conversation.
            conversationname (str): Name of the conversation.
            lastupdateddate (str): Timestamp of the last update to the conversation.
"""
from datetime import datetime
from enum import Enum
from typing import Union, List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field, field_validator
from pydantic_core import PydanticCustomError
from core.utils import generate_uuid7_id
from models.parts import TextPart, DataPart, FilePart


class Artifact(BaseModel):
  """
  Artifacts object model. Ref: https://a2a-protocol.org/dev/specification/#67-artifact-object
  @TODO: Move to common models as needed by orchestrator MCP as well. 
  """      
  artifactId: str  = Field(
        ...,
        description="A unique identifier (e.g. UUID) for the artifact within the scope of the task."
  )  
  name: Optional[str] = Field(
        default="",
        description="An optional, human-readable name for the artifact."
  )  
  description: Optional[str] = Field(
        default="",
        description="An optional, human-readable description of the artifact."
  )  
  parts: List[Union[TextPart, FilePart, DataPart]] = Field(
        ...,
        description="An array of content parts that make up the artifact."
  )  
  metadata : Optional[Dict[str, Any]] = Field(
        default={},
        description="Optional metadata for extensions. The key is an extension-specific identifier. "
  )  
  extensions: Optional[List[str]] = Field(
        default=[],
        description="The URIs of extensions that are relevant to this artifact."
  )
  
class OrchestratorAgentResponse(BaseModel):    
    """
    Model for response of Orchestrator Agent.
    @TODO: Move to common models as needed by orchestrator MCP as well. 
    """
    parts: List[Union[TextPart, FilePart, DataPart]] = Field(
        ...,
        description="Content parts of the message, which can be text, file, or data."
    )
    artifacts: Optional[List[Artifact]] = Field(default=[], description="List of artifacts")

# Request Models
class ChatMessage(BaseModel):
    role: str = Field(
        ...,
        description="Role of the message sender, either 'user' or 'agent'.",
        pattern="^(user|agent)$"
    )
    status: Optional[str] = Field(default='',description="Message status")
    id: Optional[str] = Field(
        default_factory=generate_uuid7_id,
        description="Unique identifier for the message, generated by default."
    )
    parts: List[Union[TextPart, FilePart, DataPart]] = Field(
        ...,
        description="Content parts of the message, which can be text, file, or data."
    )
    extensions: List[dict] = Field(
        default_factory=list,
        description="Optional list of extension metadata for the message. will be used to manage document handler or other references or artifacts from the response"
    )

    @field_validator('parts')
    @classmethod
    def check_message_parts(cls, message_parts: List[Union[TextPart, FilePart, DataPart]]) -> List[Union[TextPart, FilePart, DataPart]]:
        """
        Handle validation on parts such that message parts should not be empty.        
        """
        if len(message_parts) == 0:  
            raise PydanticCustomError('parts', 'Message parts can not be empty.', {'input_value': message_parts})

        # @TODO: Remove if current condtion on having first part as text message part removed.
        if message_parts[0].kind != 'text':
            raise PydanticCustomError('parts', 'First message part not text.', {'input_value': message_parts})

        return message_parts


    def get_full_text_message(self):
        if not self.parts:
            return ''
        
        text_messages = []
        for part in self.parts:
            if part.kind != 'text':
                continue
            text_messages.append(part.text)    
        return ' '.join(text_messages)


class OrchestratorChatRequest(BaseModel):
    conversationid: Optional[str] = Field(
        default=None,
        description="Identifier for the conversation."
    )
    message: Optional[ChatMessage] = Field(
        default=None,
        description="The chat message being sent."
    )

class ChatRequestErrorResponse(BaseModel):
    error: str = Field(
        ...,
        description="Error message description."
    )
    code: Optional[str] = Field(
        default=None,
        description="Optional error code."
    )
    details: Optional[dict] = Field(
        default=None,
        description="Additional details about the error."
    )


class ConversationMessage(ChatMessage):
    createddatetime: datetime = Field(
        ...,
        description="Timestamp when the message was created."
    )

class ConversationResponse(BaseModel):
    messages: List[ConversationMessage] = Field(
        ...,
        description="List of messages in the conversation."
    )

class AllConversationResponseItem(BaseModel):
    conversationid: str = Field(
        ...,
        description="Unique identifier for the conversation."
    )
    conversationname: str = Field(
        ...,
        description="Name of the conversation."
    )
    lastupdateddate: str = Field(
        ...,
        description="Timestamp of the last update to the conversation."
    )

class ConversationListResponse(BaseModel):
    items: List[AllConversationResponseItem]
    total: int

class NotificationStates(Enum):
    submitted = 'submitted'
    working = 'working'
    input_required = 'input-required'
    completed = 'completed'
    cancelled = 'cancelled'
    failed = 'failed'
    rejected = 'rejected'
    auth_required = 'auth-required'

class OrchestratorNotificationTaskStatus(BaseModel):
    state: NotificationStates = Field(..., description="The state of the task.")
    message: Optional[ChatMessage] = Field(default=None, description="Chat message response")

class OrchestratorNotificationRequest(BaseModel):
    id: str = Field(
        ...,
        description="Notification ID"
    )
    contextId: Optional[str] = Field(
        default=None,
        description="Identifier for the conversation."
    )
    status: OrchestratorNotificationTaskStatus
    kind: Literal["task"] = Field(description="Type of request message schema e.g. task")

class OrchestratorNotificationResponse(BaseModel):
    status: Literal['OK']

def get_text_and_non_text_parts(parts: List[Union[TextPart, DataPart, FilePart]]) -> tuple:                                
    """
    Separate out text and non text part form parts.
    """
    text_parts = []
    non_text_parts = []
    for part in parts:
        if part.kind == 'text':
            text_parts.append(part)
        else:
            non_text_parts.append(part)
    return text_parts, non_text_parts


def get_non_text_artifacts(non_text_parts: List[Union[DataPart, FilePart]]) -> List[Artifact]:
    """
    Get non text artifacts from given non text parts.
    Add flag to identify response artifacts.
    """
    non_text_artifacts = []
    for non_text_part in non_text_parts:
        if not (non_text_part.kind == 'data' or non_text_part.kind == 'file'):
            continue
        artifact_id = generate_uuid7_id()
        non_text_artifact = Artifact(name=artifact_id, artifactId=artifact_id, parts=[non_text_part], metadata={"source":"agent_response"})
        non_text_artifacts.append(non_text_artifact)
    return non_text_artifacts


def get_text_from_parts(text_parts: List[Union[TextPart]]) -> str:
    """
    Get text from given text parts.
    """
    text_result = ''
    for text_part in text_parts:
        if text_part.kind != 'text':
            continue
        text_result += f' {text_part.text}'
    return str(text_result).strip()

